export const MD = [
  '# heading h1',
  '## heading h2',
  '---',
  '### links',
  '[link](https://freecodecamp.org)\n',
  '---',
  '### code',
  'inline `code`\n',
  '    // block code',
  '    line 1 of code',
  '    line 2 of code',
  '    line 3 of code',
  '---',
  '### lists',
  '+ item 1\n  - item 2\n    * item 3',
  '---',
  '### blockquote',
  '> blockquote\n>> blockquote nested\n> > > ... or with between arrows',
  '---',
  '### images',
  '![Minion](https://octodex.github.com/images/minion.png)\n',
  '---',
  '### emphasis',
  '**This is bold text**',
  '__This is bold text__',
  '*This is italic text*',
  '_This is italic text_',
  '~~Strikethrough~~',
];
